import type { IContentMatch } from './IContentMatch';
import type { IFragment } from './IFragment';
import type { IMark } from './IMark';
import type { IMarkType } from './IMarkType';
import type { INodeType } from './INodeType';
import type { IResolvedPos } from './IResolvedPos';
import type { ISlice } from './ISlice';
import { NodeJSON } from './types/NodeJSON';

export interface INode {
  readonly attrs: Record<string, unknown>;
  readonly childCount: number;
  readonly content: IFragment;
  readonly firstChild: INode | undefined;
  readonly inlineContent: boolean | null;
  readonly isAtom: boolean;
  readonly isBlock: boolean;
  readonly isInline: boolean;
  readonly isLeaf: boolean;
  readonly isText: boolean;
  readonly isTextblock: boolean;
  readonly lastChild: INode | undefined;
  readonly marks: IMark[];
  readonly nodeSize: number;
  readonly text?: string;
  readonly type: INodeType;
  canAppend(other: INode): boolean;
  canReplace(from: number, to: number, replacement?: IFragment, start?: number, end?: number): boolean;
  canReplaceWith(from: number, to: number, type: INodeType, marks?: readonly IMark[]): boolean;
  child(index: number): INode;
  childAfter(pos: number): { node: INode | null; index: number; offset: number };
  childBefore(pos: number): { node: INode | null; index: number; offset: number };
  check(): void;
  contentMatchAt(pos: number): IContentMatch;
  copy(content?: IFragment): INode;
  cut(from: number, to?: number): INode;
  equals(other: INode): boolean;
  forEach(callback: (node: INode, offset: number, index: number) => void): void;
  hasMarkup(type: INodeType, attrs?: Record<string, unknown>, marks?: readonly IMark[]): boolean;
  mark(marks: IMark[]): INode;
  maybeChild(index: number): INode | null;
  nodeAt(pos: number): INode | null;
  nodesBetween(from: number, to: number, callback: (node: INode, pos: number, parent: INode | null, index: number) => void | boolean, startPos?: number): void;
  rangeHasMark(from: number, to: number, type: IMark | IMarkType): boolean;
  replace(from: number, to: number, replacement: ISlice): INode;
  resolve(pos: number): IResolvedPos;
  resolveNoCache(pos: number): IResolvedPos;
  sameMarkup(other: INode): boolean;
  slice(from: number, to?: number, includeParents?: boolean): ISlice;
  toJSON(): NodeJSON;
  toString(): string;
}
